#!/bin/bash
export PROMPT_COMMAND="history -a; ${PROMPT_COMMAND}"
export HISTCONTROL=ignorespace:ignoredups
__dir_dotfiles_startup="${DFC}/environment.d"
if [ -d "${__dir_dotfiles_startup}" ]; then
    __script_count=$(find "${__dir_dotfiles_startup}/" -name '*.bash' | wc -l | awk '{print $1}')
    if [ "${__script_count}" -gt 0 ]; then
        for plugin in "${__dir_dotfiles_startup}"/*.bash; do
            if [ -r "${plugin}" ]; then
                # shellcheck disable=SC1090
                . "${plugin}"
            fi
        done
        unset plugin
    fi
    unset __script_count
fi
unset __dir_dotfiles_startup
