#!/usr/bin/env sh
if command -v setxkbmap >/dev/null 2>&1
then
    # setxkbmap -option caps:swapescape
    setxkbmap -option ctrl:nocaps
fi
if command -v xmodmap >/dev/null 2>&1 && [ -e "${HOME}/.local/etc/itsdm/x11/keyboard" ]
then
    xmodmap "${HOME}/.local/etc/itsdm/x11/keyboard"
fi
if command -v xcape >/dev/null 2>&1
then
    xcape -e 'Shift_L=parenleft;Shift_R=parenright;Control_L=Escape'
fi
if command -v xrandr >/dev/null 2>&1
then
    xrandr --auto
fi
if command -v udiskie >/dev/null 2>&1
then
    udiskie --automount --notify --tray --file-manager=thunar &
fi
set_gtk_theme() {
    if command -v gsettings >/dev/null 2>&1
    then
        current_theme=$(gsettings get org.gnome.desktop.interface gtk-theme)
        theme_name="${1:-${current_theme}}"
        if find \
            /usr/share/themes \
            -mindepth 1 -maxdepth 1 -type d \
            -print0 \
        | xargs -0 -n1 basename \
        | sort \
        | grep -qw "${theme_name}" \
        ; then
            echo >/dev/null
            if ! [ "${current_theme}" = "${theme_name}" ]
            then
                gsettings set org.gnome.desktop.interface gtk-theme "${theme_name}"
            fi
        fi
    fi
}
set_gtk_theme 'Greybird-dark'
