#!/bin/sh
LC_ALL=C py3status "${@}" | while :
do
    read -r line
    printf '%s\n' "${line}" \
    | sed \
        -e 's/\([0-9]\)\.[0-9]\%/\1%/g' \
        -e 's/ |  | / | /g' \
        -e 's/1000 Mbit\/s/1 G\/s/g' \
        -e 's/100 Mbit\/s/100 M\/s/g' \
    || exit 1
done
