#!/bin/sh
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
XDG_DATA_DIRS="/usr/share"
XDG_DATA_DIRS="/usr/local/share:${XDG_DATA_DIRS}"
XDG_DATA_DIRS="/usr/share/xfce4:${XDG_DATA_DIRS}"
XDG_DATA_DIRS="${HOME}/.nix-profile/share:${XDG_DATA_DIRS}"
XDG_DATA_DIRS="${XDG_DATA_HOME}:${XDG_DATA_DIRS}"
export XDG_DATA_DIRS
# shellcheck source=shell/.config/user-dirs.dirs
. "${XDG_CONFIG_HOME}/user-dirs.dirs"
export XDG_DESKTOP_DIR XDG_DOWNLOAD_DIR XDG_TEMPLATES_DIR XDG_PUBLICSHARE_DIR XDG_DOCUMENTS_DIR XDG_MUSIC_DIR XDG_PICTURES_DIR XDG_VIDEOS_DIR

export AUTOENV_AUTH_FILE="${XDG_CACHE_HOME}/autoenv_authorized"
export GIMP2_DIRECTORY="${XDG_CONFIG_HOME}/gimp"
export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"
if [ ! -e "${HOME}/.ICEauthority" ]; then
    export ICEAUTHORITY="${XDG_CACHE_HOME}/.ICEauthority"
fi
export LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
export NETRC="${XDG_CONFIG_HOME}/dotsecrets/netrc/.netrc"
export NODE_REPL_HISTORY="${XDG_CACHE_HOME}/node.repl.history"
export NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME}/npm/rc
export NVM_DIR="${XDG_CONFIG_HOME}/nvm"
export PASSWORD_STORE_DIR=${XDG_CONFIG_HOME}/pass
export PIP_CONFIG_FILE="${XDG_CONFIG_HOME}/pip/conf"
export PIP_LOG_FILE="${XDG_CACHE_HOME}/pip/log"
export PROJECT_HOME="${HOME}/projects"
export PYTHON_EGG_CACHE="${XDG_CACHE_HOME}/python-eggs"
export SCREENRC="${XDG_CONFIG_HOME}/screen/rc"
export SQLITE_HISTORY=${XDG_DATA_HOME}/sqlite_history
export VAGRANT_HOME="${XDG_CONFIG_HOME}/vagrant.d"
if command -v VBoxManage >/dev/null 2>&1; then
	export VBOX_USER_HOME="${XDG_CONFIG_HOME}/virtualbox"
	VBoxManage setproperty machinefolder "${XDG_DATA_HOME}/virtualboxes"
fi
if [ -e "${XDG_CONFIG_HOME}/vim/rc.vim" ]; then
    # shellcheck disable=SC2016
    export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/rc.vim" | source $MYVIMRC'
else
    export VIMINIT=''
fi
export WORKON_HOME="${HOME}/.local/virtualenvs"
if [ ! -e "${HOME}/.Xauthority" ]; then
    export XAUTHORITY="${XDG_CACHE_HOME}/.Xauthority"
fi
export ZSH_PIP_CACHE_FILE="${XDG_CACHE_HOME}/pip/zsh"
export _Z_DATA="${XDG_CACHE_HOME}/z"
test -f "${_Z_DATA}" || touch "${_Z_DATA}" || true

curl() {
    _flags=
    if [ -e "${NETRC}" ]; then
        _flags="--netrc-file ${NETRC}"
    fi
    # shellcheck disable=SC2086
    command curl ${_flags} "${@}"
}
sbcl () {
    command sbcl --userinit "${XDG_CONFIG_HOME}/sbcl/rc" "${@}"
}
sqlite3 () {
    command sqlite3 -init "${XDG_CONFIG_HOME}/sqlite3/rc" "${@}"
}
ssh () {
    command ssh -F "${XDG_CONFIG_HOME}/ssh/config" "${@}"
}
wget() {
    command wget --hsts-file "${XDG_CACHE_HOME}/wget-hsts" "${@}"
}

