#!/bin/bash
if [ -s "${BASH_ENV}" ]; then
    . "${{BASH_ENV}"
fi
BASH_ENV=
if [ -s "${HOME}/.config/sh/rc" ]; then
    . "${HOME}/.config/sh/rc"
fi
if [ -s "${HOME}/.config/bash/options" ]; then
    . "${HOME}/.config/bash/options"
fi
export HISTFILE="${XDG_CACHE_HOME}/bash/history"
# Load all of the plugins
__dir_dotfiles_startup="${DFC}/etc/rc.d"
if [ -d "${__dir_dotfiles_startup}" ]; then
    __script_count=$(find "${__dir_dotfiles_startup}/" -name '*.bash' | wc -l | awk '{print $1}')
    if [ "${__script_count}" -gt 0 ]; then
        for plugin in ${__dir_dotfiles_startup}/*.bash; do
            if [ -r "${plugin}" ]; then
                . "${plugin}"
            fi
        done
        unset plugin
    fi
    unset __script_count
fi
unset __dir_dotfiles_startup
