#!/bin/sh
# Default permissions for new files
# User has read + write
# Group is readonly
# Other get nothing
umask 0037
# Then a few more basic paths
. "${HOME}/.config/sh/xdg"
export DFC=${XDG_CONFIG_HOME}/dotfiles.d
PATH="/bin"
PATH="/sbin:${PATH}"
PATH="/usr/bin:${PATH}"
PATH="/usr/sbin:${PATH}"
PATH="/opt/X11/bin:${PATH}"
PATH="/usr/local/bin:${PATH}"
PATH="/usr/local/sbin:${PATH}"
if [ -e "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]; then
    . ${HOME}/.nix-profile/etc/profile.d/nix.sh
    PATH="${HOME}/.nix-profile/bin:${PATH}"
fi
PATH="${HOME}/local/bin:${PATH}"
PATH="${HOME}/.local/bin:${PATH}"
PATH="${HOME}/bin:${PATH}"
export PATH
MANPATH="/usr/local/man"
MANPATH="/usr/local/share/man:${MANPATH}"
MANPATH="/usr/share/man:${MANPATH}"
MANPATH="${HOME}/.nix-profile/share/man:${MANPATH}"
export MANPATH
# This path is sourced by interactive POSIX shells
export ENV=${XDG_CONFIG_HOME}/sh/interactive
export BASH_ENV=${XDG_CONFIG_HOME}/bash/environment
export EDITOR=vim
# Load all of the plugins
__dir_dotfiles_startup="${DFC}/environment.d"
if [ -d "${__dir_dotfiles_startup}" ]; then
    __script_count=$(find "${__dir_dotfiles_startup}/" -name '*.sh' | wc -l | awk '{print $1}')
    if [ "${__script_count}" -gt 0 ]; then
        for plugin in ${__dir_dotfiles_startup}/*.sh; do
            if [ -r "${plugin}" ]; then
                . "${plugin}"
            fi
        done
        unset plugin
    fi
    unset __script_count
fi
unset __dir_dotfiles_startup
