#!/bin/sh
# Default permissions for new files
# User has read + write
# Group is readonly
# Other get nothing
umask 0037
# Then a few more basic paths
# shellcheck source=shells/.config/sh/xdg
. "${HOME}/.config/sh/xdg"
# shellcheck source=shells/.config/sh/path
. "${HOME}/.config/sh/path"
export DFC="${XDG_CONFIG_HOME}/dotfiles.d"

# This path is sourced by interactive POSIX shells
export ENV="${XDG_CONFIG_HOME}/sh/interactive"
export BASH_ENV="${XDG_CONFIG_HOME}/bash/environment"
export EDITOR=vim
# Load all of the plugins
__dir_dotfiles_startup="${DFC}/environment.d"
if [ -d "${__dir_dotfiles_startup}" ]; then
    __script_count=$(find "${__dir_dotfiles_startup}/" -name '*.sh' | wc -l | awk '{print $1}')
    if [ "${__script_count}" -gt 0 ]; then
        for plugin in "${__dir_dotfiles_startup}"/*.sh; do
            if [ -r "${plugin}" ]; then
                # shellcheck disable=SC1090
                . "${plugin}"
            fi
        done
        unset plugin
    fi
    unset __script_count
fi
unset __dir_dotfiles_startup
