#!/bin/sh
# Resetting the PATH shouldn't be strictly necessary here;
# we do it because root/OS startup for interactive shells prepends the
# NIX paths, even though we've already added them ourselves :shrug:
# shellcheck source=shells/.config/sh/path
. "${HOME}/.config/sh/path"
if command -v fortune >/dev/null 2>&1; then
    echo; echo
    if command -v cowsay >/dev/null 2>&1; then
        fortune | cowsay -f /dev/null
    else
        fortune
    fi
    echo
fi
# Configure common interactive shells
export HISTFILE="${XDG_STATE_HOME}/sh/history"
export HISTSIZE=10000
export HISTFILESIZE=1000000
# for OSX
export CLICOLOR_FORCE=1

# Load all of the plugins
__dir_dotfiles_startup="${DFC}/interactive.d"
if [ -d "${__dir_dotfiles_startup}" ]; then
    __script_count=$(find "${__dir_dotfiles_startup}/" -name '*.sh' | wc -l | awk '{print $1}')
    if [ "${__script_count}" -gt 0 ]; then
        for plugin in "${__dir_dotfiles_startup}"/*.sh; do
            if [ -r "${plugin}" ]; then
                # shellcheck disable=SC1090
                . "${plugin}"
            fi
        done
        unset plugin
    fi
    unset __script_count
fi
unset __dir_dotfiles_startup
