#!/bin/sh
PATH="/bin"
PATH="/sbin:${PATH}"
PATH="/usr/bin:${PATH}"
PATH="/usr/sbin:${PATH}"
PATH="/usr/games:${PATH}"
PATH="/opt/X11/bin:${PATH}"
PATH="/usr/local/bin:${PATH}"
PATH="/usr/local/sbin:${PATH}"
PATH="/nix/var/nix/profiles/default/bin:${PATH}"
PATH="${HOME}/.nix-profile/bin:${PATH}"
if [ -e "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]; then
    # shellcheck disable=SC1090
    . "${HOME}/.nix-profile/etc/profile.d/nix.sh"
elif [ -e "/etc/profile.d/nix.sh" ]; then
    # shellcheck disable=SC1090,SC1091
    . '/etc/profile.d/nix.sh'
fi
PATH="${HOME}/local/bin:${PATH}"
PATH="${HOME}/.local/bin:${PATH}"
PATH="${HOME}/bin:${PATH}"
export PATH

MANPATH="/usr/local/man"
MANPATH="/usr/local/share/man:${MANPATH}"
MANPATH="/usr/share/man:${MANPATH}"
MANPATH="${HOME}/.nix-profile/share/man:${MANPATH}"
MANPATH="${XDG_DATA_HOME}/man:${MANPATH}"
export MANPATH

# https://stackoverflow.com/a/53825858
_preload=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0
if [ -e "${_preload}" ]; then
    export LD_PRELOAD=${_preload}:${LD_PRELOAD}
fi
