#!/bin/bash
# shellcheck disable=SC2034

# Index of the first item in the menu.
countfrom=0

# Set default display.
display=0

# Where should the first X tty be spawned?
# special value `keep' causes to run X in current tty.
xtty=keep

# Should cdm(1) stick to the specified display?
locktty=false

# Additional arguments to pass to X server, which is usually called as:
#   /usr/bin/X :$display "${serverargs[@]}" vt$((xtty+display))
# Arguments with whitespaces should be quoted or escaped.
serverargs=(-nolisten tcp)

# Alternative method of calling startx(/setsid). Should only be set if cdm
# does not start X as expected (bash -x shows call to setsid startx, but for
# no apparent reason does not start X).
# Only provided in the hope it may be useful, not a guaranteed fix.
altstartx=false

# Destination for stdout and stderr output from startx.
startxlog=/dev/null
