---
name: Validate changeset
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  bootstrap:
    strategy:
      matrix:
        os:
        - debian-bullseye
        - debian-buster
        - debian-sid
        - ubuntu-bionic
        - ubuntu-impish
        - ubuntu-jammy
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get clean --fix-missing
    - run: sudo apt-get update --fix-missing
    - name: Install everything from scratch
      run: make from-scratch
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
        - debian-bullseye
        - debian-buster
        - debian-sid
        - ubuntu-bionic
        - ubuntu-impish
        - ubuntu-jammy
    steps:
    - uses: actions/checkout@v2
    - name: Build a docker container
      run: make docker.build.${{ matrix.os }}
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the linter
      run: make lint
