---
name: Validate changeset
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  bootstrap:
    strategy:
      fail-fast: false
      matrix:
        os:
        - debian-bullseye
        - debian-buster
        - debian-stretch
        - ubuntu-bionic
        - ubuntu-focal
        - ubuntu-jammy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get clean --fix-missing
    - run: sudo apt-get update --fix-missing
    - name: Install everything from scratch
      env:
        DOCKER_OS: '${{ matrix.os }}'
      run: make docker.from-scratch
  devstack:
    strategy:
      fail-fast: false
      matrix:
        os:
        - debian-bullseye
        - debian-buster
        - debian-stretch
        - ubuntu-bionic
        - ubuntu-focal
        - ubuntu-jammy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the sandbox
      env:
        DOCKER_OS: '${{ matrix.os }}'
      run: make docker.build
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the linter
      run: make lint
