---
name: Validate changeset
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install everything from scratch
      run: make from-scratch
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build a docker container
      run: make docker.build
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the linter
      run: make lint
  lint-diff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the linter against changed files only
      run: make lint.diff
